"""add_model_versions

Revision ID: 38c0ecb62244
Revises: 75032f7fb007
Create Date: 2026-07-11 19:51:14.313672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38c0ecb62244'
down_revision: Union[str, None] = '75032f7fb007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('parent_version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_label', 'market', name='uq_version_market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_versions')
    # ### end Alembic commands ###
