"""initial

Revision ID: 75032f7fb007
Revises: 
Create Date: 2026-07-11 17:07:08.174549
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75032f7fb007'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=10), nullable=False),
    sa.Column('away_team', sa.String(length=10), nullable=False),
    sa.Column('park', sa.String(length=50), nullable=True),
    sa.Column('home_pitcher_id', sa.String(length=20), nullable=True),
    sa.Column('away_pitcher_id', sa.String(length=20), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team'), 'games', ['away_team'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team'), 'games', ['home_team'], unique=False)
    op.create_table('park_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('park', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('hr_factor', sa.Float(), nullable=False),
    sa.Column('runs_factor', sa.Float(), nullable=False),
    sa.Column('single_factor', sa.Float(), nullable=False),
    sa.Column('double_factor', sa.Float(), nullable=False),
    sa.Column('triple_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_park_factors_park'), 'park_factors', ['park'], unique=False)
    op.create_table('batters_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batter_id', sa.String(length=20), nullable=False),
    sa.Column('batter_name', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('opponent', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('avg_rolling_15', sa.Float(), nullable=True),
    sa.Column('woba_rolling_15', sa.Float(), nullable=True),
    sa.Column('exit_velocity_avg', sa.Float(), nullable=True),
    sa.Column('barrel_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batters_game_log_batter_id'), 'batters_game_log', ['batter_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=20), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_game_id'), 'lineups', ['game_id'], unique=False)
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_game_id'), 'odds_history', ['game_id'], unique=False)
    op.create_index(op.f('ix_odds_history_timestamp'), 'odds_history', ['timestamp'], unique=False)
    op.create_table('pitchers_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pitcher_id', sa.String(length=20), nullable=False),
    sa.Column('pitcher_name', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('opponent', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('ip', sa.Float(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('er', sa.Integer(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.Column('avg_velocity', sa.Float(), nullable=True),
    sa.Column('era_rolling_15', sa.Float(), nullable=True),
    sa.Column('era_rolling_30', sa.Float(), nullable=True),
    sa.Column('fip_rolling_15', sa.Float(), nullable=True),
    sa.Column('k9_rolling', sa.Float(), nullable=True),
    sa.Column('bb9_rolling', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitchers_game_log_pitcher_id'), 'pitchers_game_log', ['pitcher_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=100), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('simulated_median', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_game_id'), 'predictions', ['game_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('conditions', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_game_id'), 'weather', ['game_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('closing_line_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('closing_line_prob', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_prediction_id'), 'results', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_prediction_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_weather_game_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_predictions_game_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_pitchers_game_log_pitcher_id'), table_name='pitchers_game_log')
    op.drop_table('pitchers_game_log')
    op.drop_index(op.f('ix_odds_history_timestamp'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_game_id'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_lineups_game_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_batters_game_log_batter_id'), table_name='batters_game_log')
    op.drop_table('batters_game_log')
    op.drop_index(op.f('ix_park_factors_park'), table_name='park_factors')
    op.drop_table('park_factors')
    op.drop_index(op.f('ix_games_home_team'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
